[package]
name = "aoc_2019"
version = "0.1.0"
authors = ["Keith Wissing <keith_wissing@bradycorp.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
